# Generated by Django 4.2.4 on 2023-09-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0002_entregable'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fech_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
